name: Build and Release

on:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4.1.5

      - name: Setup JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: "17"

      - name: Set execution flag for gradlew
        run: chmod +x gradlew

      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v3

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'esapmobile.jks'
          fileDir: '/home/runner/work/mobile/app/keystore/'
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Build APK
        run: bash ./gradlew clean :app:assembleRelease -x test --no-daemon
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Retrieve Version
        id: android_version
        run: echo "VERSION_NAME=$(./gradlew -q printVersionName)" >> version.txt

      - name: Upload APK and Version
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            app/build/outputs/apk/release/EsapMobile.apk
            version.txt

  release:
    name: Release APK
    needs: apk
    runs-on: ubuntu-latest
    steps:

      - name: Download build output
        uses: actions/download-artifact@v4.1.7
        with:
          name: build-output
          path: download

      - name: Read Version
        id: read_version
        run: echo "VERSION_NAME=$(cat download/version.txt | grep VERSION_NAME | cut -d'=' -f2)" >> $GITHUB_ENV

      - uses: kaisugi/action-regex-match@v1.0.0
        id: regex-match
        with:
          text: ${{ github.event.head_commit.message }}
          regex: '^v[0-9]+\.[0-9]+\.[0-9]+$'

      - name: Build Changelog
        if: ${{ steps.regex-match.outputs.match != '' }}
        id: changelog
        uses: ardalanamini/auto-changelog@v3
        with:
          mention-authors: false
          mention-new-contributors: false
          include-compare: false
          semver: false

      - name: Create Release
        if: ${{ steps.regex-match.outputs.match != '' }}
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION_NAME }}
          release_name: ${{ github.event.repository.name }} v${{ env.VERSION_NAME }}

      - name: Upload Release APK
        if: ${{ steps.regex-match.outputs.match != '' }}
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: download/app/build/outputs/apk/release/EsapMobile.apk
          asset_name: EsapMobile-v${{ env.VERSION_NAME }}.apk
          asset_content_type: application/zip
          body: ${{ steps.changelog.outputs.changelog }}